[package]
name = "snazlock"
version = "0.1.0"
authors = ["Miles Steele <miles@milessteele.com>"]

[dependencies]
pam-auth = "0.4.0"
rpassword = "0.3.0"
users = "0.5.2"
piston = "0.26.0"
piston2d-graphics = "0.18.0"
pistoncore-glutin_window = "0.31.0"
piston2d-opengl_graphics = "0.35.0"
